# Max Voting

In [1]:
%cd '/content/drive/MyDrive/Machine Learning/13. Basics of Ensemble models'

/content/drive/MyDrive/Machine Learning/13. Basics of Ensemble models


In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('data_cleaned.csv')

In [4]:
data.shape

(891, 25)

In [5]:
data.head()

Survived   Age     Fare  ...  Embarked_C  Embarked_Q  Embarked_S
0         0  22.0   7.2500  ...           0           0           1
1         1  38.0  71.2833  ...           1           0           0
2         1  26.0   7.9250  ...           0           0           1
3         1  35.0  53.1000  ...           0           0           1
4         0  35.0   8.0500  ...           0           0           1

[5 rows x 25 columns]

In [6]:
#seperating independent and dependent variables

x = data.drop(['Survived'], axis=1)
y = data['Survived']

In [7]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, stratify=y)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [9]:
model1 = LogisticRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


(array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0]), 0.7757847533632287)

In [10]:
model2 = KNeighborsClassifier(n_neighbors=5)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0]), 0.7399103139013453)

In [11]:
model3 = DecisionTreeClassifier(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0]), 0.7847533632286996)

In [12]:
# df = pd.DataFrame(columns=['M1', 'M2', 'M3', 'Actual'])
# df['M1'] = pred1
# df['M2'] = pred2
# df['M3'] = pred3
# df['Actual'] = np.array(valid_y)

In [15]:
from statistics import mode
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mode([pred1[i], pred2[i], pred3[i]]))

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(valid_y, final_pred)

0.8071748878923767

In [18]:
accuracy_score(valid_y, pred1), accuracy_score(valid_y, pred2), accuracy_score(valid_y, pred3)

(0.7757847533632287, 0.7399103139013453, 0.7847533632286996)

# Averaging

In [19]:
data=pd.read_csv('train_cleaned.csv')

In [20]:
#seperating independent and dependent variables
x = data.drop(['Item_Outlet_Sales'], axis=1)
y = data['Item_Outlet_Sales']

In [21]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [23]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([ 2443.32513354,  2788.36657095,  2169.73477778,  2385.33394477,
         2716.58813899,  3771.41850023,  5119.35227101,  4133.40997069,
        -1010.95412123,  1365.9929378 ]), 0.5551582433748832)

In [24]:
model2 = KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1859.06155556, 2519.09128889, 2620.88471111, 2277.33191111,
        3801.12617778, 4099.10866667, 5151.88642222, 5378.62831111,
         476.7128    , 1501.15706667]), 0.5007936087911619)

In [25]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]), 0.5735111622038214)

In [26]:
from statistics import mean
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred2[i], pred3[i]]))

In [27]:
from sklearn.metrics import r2_score

In [28]:
r2_score(valid_y, final_pred)

0.5761404444862531

In [29]:
r2_score(valid_y, pred1), r2_score(valid_y, pred2), r2_score(valid_y, pred3)

(0.5551582433748832, 0.5007936087911619, 0.5735111622038214)

# Weighted Averaging

In [30]:
data=pd.read_csv('train_cleaned.csv')

In [31]:
#seperating independent and dependent variables
x = data.drop(['Item_Outlet_Sales'], axis=1)
y = data['Item_Outlet_Sales']

In [32]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [34]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([ 2443.32513354,  2788.36657095,  2169.73477778,  2385.33394477,
         2716.58813899,  3771.41850023,  5119.35227101,  4133.40997069,
        -1010.95412123,  1365.9929378 ]), 0.5551582433748832)

In [35]:
model2 = KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1859.06155556, 2519.09128889, 2620.88471111, 2277.33191111,
        3801.12617778, 4099.10866667, 5151.88642222, 5378.62831111,
         476.7128    , 1501.15706667]), 0.5007936087911619)

In [36]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]), 0.5734613370524885)

In [37]:
from statistics import mean
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred1[i], pred2[i], pred3[i], pred3[i]]))

In [38]:
from sklearn.metrics import r2_score

In [39]:
r2_score(valid_y, final_pred)

0.5810435265494609

In [40]:
r2_score(valid_y, pred1), r2_score(valid_y, pred2), r2_score(valid_y, pred3)

(0.5551582433748832, 0.5007936087911619, 0.5734613370524885)

# Rank Averaging

In [41]:
data=pd.read_csv('train_cleaned.csv')

In [42]:
#seperating independent and dependent variables
x = data.drop(['Item_Outlet_Sales'], axis=1)
y = data['Item_Outlet_Sales']

In [43]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [45]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([ 2443.32513354,  2788.36657095,  2169.73477778,  2385.33394477,
         2716.58813899,  3771.41850023,  5119.35227101,  4133.40997069,
        -1010.95412123,  1365.9929378 ]), 0.5551582433748832)

In [46]:
model2 = KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1859.06155556, 2519.09128889, 2620.88471111, 2277.33191111,
        3801.12617778, 4099.10866667, 5151.88642222, 5378.62831111,
         476.7128    , 1501.15706667]), 0.5007936087911619)

In [47]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]), 0.5734894559704367)

In [48]:
m1_score= model1.score(valid_x, valid_y)
m2_score= model2.score(valid_x, valid_y)
m3_score= model3.score(valid_x, valid_y)
m1_score, m2_score, m3_score

(0.5551582433748832, 0.5007936087911619, 0.5734894559704367)

In [49]:
index_ = [1,2,3]
valid_r2 = [m1_score,m2_score,m3_score]

rank_eval = pd.DataFrame({
    'score':valid_r2
}, index = index_)
rank_eval

score
1  0.555158
2  0.500794
3  0.573489

In [50]:
sorted_rank = rank_eval.sort_values('score')
sorted_rank

score
2  0.500794
1  0.555158
3  0.573489

In [51]:
sorted_rank['rank'] = [i for i in range(1,4)]
sorted_rank

score  rank
2  0.500794     1
1  0.555158     2
3  0.573489     3

In [52]:
sorted_rank['weight'] = sorted_rank['rank']/sorted_rank['rank'].sum()
sorted_rank

score  rank    weight
2  0.500794     1  0.166667
1  0.555158     2  0.333333
3  0.573489     3  0.500000

In [53]:
wt_pred1 = pred1*float(sorted_rank.loc[[1],['weight']].values)
wt_pred2 = pred2*float(sorted_rank.loc[[2],['weight']].values)
wt_pred3 = pred3*float(sorted_rank.loc[[3],['weight']].values)
ranked_prediction = wt_pred1 + wt_pred2 + wt_pred3
ranked_prediction

array([2331.19418533, 2760.66363737, 1452.6721998 , ..., 1348.78554185,
       1570.52823782, 1268.26795746])

In [54]:
r2_score(valid_y, ranked_prediction)

0.5828004089407794